name: Chocolatine
run-name: check_if_the_push_or_the_pull_is_good
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_coding_style:
    name: check_coding_style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: check.sh $(pwd) $(pwd)
      - run: if [ -f coding-style-reports.log ]; then
              cat coding-style-reports.log