name: Chocolatine
run-name: check_if_the_push_or_the_pull_is_good
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_coding_style:
    name: check_coding_style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          check.sh $(pwd) $(pwd)
          if [ -f coding-style-reports.log ]; then
            cat coding-style-reports.log
          fi

  check_program_compilation:
    name: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    env:
      EXECUTABLES: "104neutrinos"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compilation
        run: make
        timeout-minutes: 2
      - name: Cleaner
        run: make clean
      - name: Check file exist
        run: |
          if [ -f 104neutrinos ]; then
            if [ -x 104neutrinos ]; then
              echo "Le fichier existe et est exécutable."
            else
              echo "Le fichier existe mais n'est pas exécutable."
              exit 1
            fi
          else
            echo "Le fichier n'existe pas."
            exit 1
          fi

  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compilation
        run: make tests_run
        timeout-minutes: 2